DiscordBot:
  Token: null
  GuildId: null
  StatusText: github.com/BIOS9/ECSDiscord
SendGrid:
  FromAddress: null
  FromName: null
  ApiKey: null
Enrollments:
  RequireVerificationToJoin: true
Verification:
  EmailPattern: "^([a-z0-9]{1,30})@(ecs\\.vuw|myvuw)\\.ac\\.nz$"
  UsernamePatternGroup: 1
  MailSubjectTemplate: null
  MailBodyTemplate: null
  MailBodyIsHtml: false
  VerifiedRoleId: null
  MutedRoleId: null
  PublicKeyPath: null
PrefixCommands:
  Prefix: +
Storage:
  ConnectionString: Server=<server>;Port=3306;Database=<db>;Uid=<user>;Pwd=<password>;
courses:
  defaultChannelPermissions:
    allowed:
      everyone: 0
      joined: 1024
      verified: 0
    denied:
      everyone: 1024
      joined: 0
      verified: 0
  channelRolePermissionOverrides:
    example:
      roleId: null
      allowed: 0
      denied: 0
Serilog:
  WriteTo:
    - Console
  MinimumLevel:
    Default: Verbose