name: .NET Build

on:
  push:
    branches: [ '**' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4.3.1
      with:
        dotnet-version: '8.0.x'
        
    - name: Install dependencies
      run: dotnet restore
      working-directory: ./src
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: ./src
      
    - name: Execute unit tests
      run: dotnet test --configuration Release --no-build
      working-directory: ./src
